import React, { useState } from "react";
import type { NextPage } from "next";
import FooterComplaints from "../../Components/FooterComplaints";
import NavBar from "../../Components/NavBar";
import Head from "next/head";

const index: NextPage = (props) => {
	const [showScam, setShowScam] = useState(false);
	const [year, setYear] = useState(10);
	const getYears = [
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
		{
			year: 2010,
		},
	];
	return (
		<>
			<Head>
				<title>Ecommerce Complaint</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				{/* <link
					href="https://unpkg.com/aos@2.3.1/dist/aos.css"
					rel="stylesheet"
				></link> */}
			</Head>
			<div className="bg-clearblue">
				<NavBar hasWhiteText={true} />
				<div className="relative mx-auto text-center bg-eccblue">
					<p className="mx-auto text-[30px] text-5xl font-bold text-white pt-48 pb-[233px]">
						Be informed, stay woke,
						<br /> stay smart!
					</p>
					{/* <img src="./images/look.png" alt="" className="mx-auto" /> */}
					{/* <div className="rounded-xl mx-[141px] bg-[#fff] xl:w-[80.4%] absolute -bottom-[10%] drop-shadow-md">
					<form className="xl:pl-[28px] xl:pr-[288px] xl:py-[34px] relative flex items-center space-x-[45px]">
						<img
							src="./icons/search.svg"
							className="w-[38px] h-[38px]"
							alt=""
						/>
						<input
							type="text"
							className="w-full text-xl"
							placeholder="Search for phone number, social media handle, Bank details and website"
						/>
						<input
							type="submit"
							value="Search"
							onClick={(e) => e.preventDefault()}
							className="bg-eccblue rounded-xl xl:px-12 xl:py-3.5 text-white placeholder:text-xl absolute right-[93px]"
						/>
					</form>
				</div> */}
					<div className="rounded-xl absolute left-[50%] -translate-x-2/4 -bottom-[55px] py-[27px] bg-[#ff1333] w-[80.6%] max-w-[1159px] px-5">
						<form className="flex space-x-[20px] items-center justify-between">
							<div>
								
							</div>
							<p className="text-left text-eccblue font-medium">Scam Year / Season</p>
							<div className="bg-grey-100 rounded-xl w-full flex items-center text-grey-200 cursor-pointer">
								<div className="flex justify-between py-4 px-4 w-full">
									<p>Choose a car:</p>
									<img
										src="./icons/chevron-down.svg"
										className=""
										alt=""
									/>
								</div>
								<div></div>
							</div>
							{/* </div> */}
							{/* <div>
							<p className="font-medium text-left">
								Scam Year / Season
							</p>
							<input
								type="text"
								className="bg-[#F0F0F0] rounded-[12px] px-[86px] placeholder:text-left text-grey-200 box-border"
								placeholder={new Date()
									.getFullYear()
									.toString()}
							/>
						</div> */}
							{/* <div className="w-[30.5%]">
							<label htmlFor="year"></label>
							<input
								type="text"
								className="h-14 bg-grey-100 rounded-xl w-full px-4"
							/>
						</div> */}
							<div className="w-full">
								<p className="text-left text-eccblue font-medium">Scam Year / Season</p>
								<div className="relative bg-grey-100 rounded-xl text-grey-200 select-none">
									<div
										className="flex justify-between py-4 px-4 w-full cursor-pointer"
										onClick={() => setShowScam(!showScam)}
									>
										<p>
											{year
												? year
												: new Date()
														.getFullYear()
														.toString() +
												  "(Current Year)"}
											{}{" "}
										</p>
										<img
											src="./icons/chevron-down.svg"
											className=""
											alt=""
										/>
									</div>
									{showScam && (
										<div
											className={`absolute top-[44px] right-0 bg-grey-100 -z-10 rounded-b-xl drop-shadow-md`}
											data-aos="slide-down"
											data-aos-offset="100"
										>
											<div className="w-full h-full flex flex-col space-y-[5px] px-[20px] py-[10px]">
												{getYears.map((year, index) => (
													<p
														className="cursor-pointer hover:text-darkblue duration-150"
														onClick={() => {
															setYear(year.year);
															setShowScam(false);
														}}
														key={index}
													>
														{year.year}
													</p>
												))}
											</div>
										</div>
									)}
								</div>
							</div>
							<input
								type="submit"
								className="bg-darkblue rounded-[12px] py-5 px-[27px] max-h-14 text-left text-sm text-white cursor-pointer font-semibold"
								value={"View Stats"}
							/>
						</form>
					</div>
				</div>

				<div className="bg-clearblue mt-[115px]">
					<div className="pt-[90px] pl-[140px]">
						<div>
							<p className="text-[24px]">
								Showing{" "}
								<span className="text-[#0B63C5]">
									All Scam types
								</span>{" "}
								stats for{" "}
								<span className="text-[#0B63C5]">2022</span>
							</p>
						</div>
						<div className="flex flex-row w-auto h-auto bg-white mr-[141px] rounded-[12px] mt-[20px] pb-[39px] space-x-[250px]">
							<div>
								<p className="text-[25px] font-semibold pt-[40px] pl-[25px]">
									$350,000,000
								</p>
								<p className="pl-[25px] font-light pt-[12px]">
									Amount Lost
								</p>
							</div>
							<div className="border-l-2">
								<p className="text-[25px] font-semibold pt-[40px] pl-[25px]">
									150,000,000
								</p>
								<p className="pl-[25px] font-light pt-[12px]">
									Number of Reports
								</p>
							</div>
							<div className="border-l-2">
								<p className="text-[25px] font-semibold pt-[40px] pl-[25px]">
									18%
								</p>
								<p className="pl-[25px] font-light pt-[12px]">
									Reports with financial losses
								</p>
							</div>
						</div>
						<div className="w-auto h-[628px] bg-[#fff] mr-[141px] mt-[28px] rounded-[12px]">
							<div>
								<p>Chart goes here</p>
							</div>
						</div>
						<div className="flex flex-row space-x-[28px]">
							<div className="w-[570px] h-[752px] bg-[#fff] rounded-[12px] mt-[28px]">
								<p>Chart goes here</p>
							</div>
							<div className="w-[570px] h-[752px] bg-[#fff] rounded-[12px] mt-[28px]">
								<p>Chart goes here</p>
							</div>
						</div>
					</div>
				</div>
				<FooterComplaints />
			</div>
		</>
	);
};

export default index;
